---
bind_address: 0.0.0.0:27690
bind_attempts: 3
mode: udp
server_cert: "tests/certs/server.crt"
server_key: "tests/certs/server.key"
tun_name: lightway
ip_pool: 10.125.0.0/16
tun_ip: 10.125.0.1
# ip_map: /path/to/ip_map.yaml
# -or-
# ip_map:
#   172.16.0.1: 10.125.128.0/28
#   192.168.1.1: 10.125.128.16/28
lightway_server_ip: 10.125.0.1
lightway_client_ip: 10.125.0.2
lightway_dns_ip: 169.254.10.5
log_format: full
log_level: info
enable_pqc: false
enable_tun_iouring: false
# iouring_sqpoll_idle_time: 100ms
iouring_entry_count: 1024
key_update_interval: 15m
user_db: "scripts/cfg/lwpasswd"
udp_buffer_size: 15 MiB
generic_insert_cmd: ["tunnel_inserter",
                    "-o", "{outside}",
                    "-c", "{control}",
                    "--stderr-file", "/tmp/brt_server_log.txt",
                    "--local-addr", "10.125.0.1",
                    "--remote-addr", "10.125.0.2",
                    "--local-ports", "9000", "9001", "9002", "9003",
                    "--remote-ports", "9003", "9002", "9001", "9000",
                    "--",
                    "bitripple_tunnel",
                    "-x", "tun-fd={inside}",
                    "-x", "tx-sock-fd={fd0}",
                    "-x", "feedback-tx-sock-fd={fd1}",
                    "-x", "feedback-rx-sock-fd={fd2}",
                    "-x", "rx-sock-fd={fd3}",
                    ]
