[package]
name = "bitripple_factory_thin_wrapper"
version = "1.0.19"
edition.workspace = true
publish = false

[dependencies]
bytes.workspace = true
lightway-app-utils.workspace = true
lightway-core.workspace = true
lt3_plugin = { git = "ssh://git@github.com/BitRipple-Inc/lt3_plugin.git", rev = "403e6255600c10b9426bae824524d6ae5a052a5e" }
serde.workspace = true
serde_json = "1.0.149"

[lints]
workspace = true
