[package]
name = "bitripple_factory_thin_wrapper"
version = "1.0.14"
edition.workspace = true
publish = false

[dependencies]
lightway-core.workspace = true
lightway-app-utils.workspace = true
anyhow.workspace = true
bytes.workspace = true
thiserror.workspace = true
tokio.workspace = true
lt3_plugin = { git = "https://github.com/BitRipple-Inc/lightway_bitripple_plugin.git", branch = "windows-support" }

[dev-dependencies]
rand = "0.9.0"

[lints]
workspace = true
