[package]
name = "bitripple_factory_thin_wrapper"
version = "1.0.17"
edition.workspace = true
publish = false

[dependencies]
lightway-core.workspace = true
lightway-app-utils.workspace = true
anyhow.workspace = true
bytes.workspace = true
thiserror.workspace = true
tokio.workspace = true
nix = { version = "0.29.0", features = ["poll", "socket", "fs"] }
lt3_plugin = { git = "ssh://git@github.com/BitRipple-Inc/lt3_plugin.git", tag = "v1.0.17" }

[dev-dependencies]
rand = "0.9.0"

[lints]
workspace = true
