# .github/workflows/ci.yml
name: CI
on:
  # Running CI on all commits on all branches (implicitly covers pull request too)
  push:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress:  ${{ github.ref_name != 'main' }}

jobs:
  ci:
    needs: [nix-build]
    runs-on: ubuntu-latest
    if: always()
    steps:
      - shell: bash
        run: |
          [[ $(echo '${{ toJSON(needs) }}' | jq 'map(select(.result != "success")) | length == 0') == 'true' ]] || exit 1

  nix-build:
    name: Nix (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest]
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v31
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - run: nix flake check

      - name: Build lightway client
        run: nix build .#lightway-client

      - name: Build lightway server
        run: nix build .#lightway-server
